### ISSUE TITLE
Добавить поддержку typescript

### ISSUE THREAD

**Issue by devnaumov** [node-vk-bot-api/node-vk-bot-api#108]
Есть ли возможность добавить поддержку typescript?

**Comment by mihett05** [comment]
Для создания ботов на ts существует vk-io

**Comment by feddot2517** [comment]
Сделал форк, добавил поддержку TS

**Comment by GiddeonWyeth** [comment]
@feddot2517 Appreciate your work but should notice that some of your typings are incorrect. Some of them contain just wrong type like `string` instead of `number` which is bad but acceptable and some contain completely invalid typing which prevents correct usage and leads to syntax errors. For example typings for middleware which are described as arrays but they should not be passed as array. Be aware
